declare module 'lucide-react' {
  import { ForwardRefExoticComponent, RefAttributes, SVGProps } from 'react';

  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
    color?: string;
    strokeWidth?: string | number;
  }

  export type LucideIcon = ForwardRefExoticComponent<LucideProps & RefAttributes<SVGSVGElement>>;

  export const Activity: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const ArrowDownToLine: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const Award: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Briefcase: LucideIcon;
  export const Building2: LucideIcon;
  export const Calendar: LucideIcon;
  export const Camera: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const CheckIcon: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronDownIcon: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronRightIcon: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Clock: LucideIcon;
  export const CloudUpload: LucideIcon;
  export const Copy: LucideIcon;
  export const Disc: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Download: LucideIcon;
  export const Edit3: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const FileAudio: LucideIcon;
  export const FileImage: LucideIcon;
  export const FileSearch: LucideIcon;
  export const FileText: LucideIcon;
  export const FileVideo: LucideIcon;
  export const Film: LucideIcon;
  export const Filter: LucideIcon;
  export const FolderPlus: LucideIcon;
  export const Globe: LucideIcon;
  export const Globe2: LucideIcon;
  export const GripVertical: LucideIcon;
  export const Headphones: LucideIcon;
  export const Image: LucideIcon;
  export const Info: LucideIcon;
  export const Languages: LucideIcon;
  export const Layers: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const LayoutGrid: LucideIcon;
  export const Link: LucideIcon;
  export const Link2: LucideIcon;
  export const ListPlus: LucideIcon;
  export const Loader2: LucideIcon;
  export const Lock: LucideIcon;
  export const LogOut: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const Medal: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Mic2: LucideIcon;
  export const MonitorPlay: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const MousePointer2: LucideIcon;
  export const Music: LucideIcon;
  export const Music2: LucideIcon;
  export const Music4: LucideIcon;
  export const Pause: LucideIcon;
  export const Phone: LucideIcon;
  export const Play: LucideIcon;
  export const Plus: LucideIcon;
  export const Radio: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const Save: LucideIcon;
  export const School: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Settings: LucideIcon;
  export const Settings2: LucideIcon;
  export const Share2: LucideIcon;
  export const Shield: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const SkipBack: LucideIcon;
  export const SkipForward: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Star: LucideIcon;
  export const Tag: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Trophy: LucideIcon;
  export const Upload: LucideIcon;
  export const UploadCloud: LucideIcon;
  export const User: LucideIcon;
  export const Users: LucideIcon;
  export const Volume2: LucideIcon;
  export const VolumeX: LucideIcon;
  export const X: LucideIcon;
  export const XCircle: LucideIcon;
  export const XIcon: LucideIcon;
  export const Zap: LucideIcon;
}

declare module 'music-metadata' {
  export const parseBuffer: (buffer: Uint8Array, options?: Record<string, unknown>) => Promise<any>;
  export const parseStream: (stream: any, options?: Record<string, unknown>) => Promise<any>;
  export const parseFile: (path: string, options?: Record<string, unknown>) => Promise<any>;
  export const parseBlob: (blob: Blob, options?: Record<string, unknown>) => Promise<any>;
}
